package view;
import Model.*;
import com.sun.crypto.provider.RSACipher;
import controller.Controller2;
import java.awt.List;
import java.sql.*;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author Eric
 */
public class mainWindow extends javax.swing.JFrame {

    
    //-------------------------------
    Controller2 controller;
    
    
    public void setController(Controller2 ct)
    {
        this.controller = ct;
        
    }
    //-------------------------------
    
    
    /**
     * Creates new form mainWindow
     */
    public mainWindow() {
        initComponents();       
    }

  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        studentAdmin = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        getStudents = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Eric", "ÖVG 47"},
                {"Hej", "Nej"}
            },
            new String [] {
                "Namn", "Adress"
            }
        ));
        jScrollPane1.setViewportView(studentTable);

        getStudents.setText("Get All Students");
        getStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getStudentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentAdminLayout = new javax.swing.GroupLayout(studentAdmin);
        studentAdmin.setLayout(studentAdminLayout);
        studentAdminLayout.setHorizontalGroup(
            studentAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(getStudents)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        studentAdminLayout.setVerticalGroup(
            studentAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getStudents)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Studentadministration", studentAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getStudentsActionPerformed
        try {
            ResultSet studentData = controller.getAllStudents();
            ResultSetMetaData studentMetaData = studentData.getMetaData();
            
          // names of columns
    Vector<String> columnNames = new Vector<String>();
    int columnCount = studentMetaData.getColumnCount();
    for (int column = 2; column <= columnCount; column++) {
        columnNames.add(studentMetaData.getColumnName(column));
    }

    // data of the table
    Vector<Vector<Object>> data = new Vector<Vector<Object>>();
    while (studentData.next()) {
        Vector<Object> vector = new Vector<Object>();
        for (int columnIndex = 2; columnIndex <= columnCount; columnIndex++) {
            vector.add(studentData.getObject(columnIndex));
        }
        data.add(vector);
    }

   this.studentTable.setModel(new DefaultTableModel(data, columnNames));
            

            
            /* for(int i=0;i < hej ;i++) {
             
              al[i] = "test";
            }*/
          
        } catch (SQLException ex) {
            Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
    }//GEN-LAST:event_getStudentsActionPerformed

    private void updateStudents() {
        try {
            ResultSet rs = controller.getAllStudents();
            ResultSetMetaData md = rs.getMetaData();
            
           
            
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton getStudents;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JPanel studentAdmin;
    private javax.swing.JTable studentTable;
    // End of variables declaration//GEN-END:variables
}
